sudo: required

services:
  - docker

language: php

env:
  global:
    - BEDITA_API_KEY=12345
    - BEDITA_API=http://127.0.0.1:8080

before_install:
  # Use GitHub OAuth token with Composer to increase API limits.
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
  - curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x wait-for-it.sh
  - docker pull bedita/bedita:latest
  - docker run -d -p 127.0.0.1:8080:80 --env BEDITA_API_KEY=${BEDITA_API_KEY} --env BEDITA_ADMIN_USR=admin --env BEDITA_ADMIN_PWD=admin bedita/bedita:latest
  - docker ps -a
  - sleep 10
  - ./wait-for-it.sh 127.0.0.1:8080 -s -t 60 -- echo 'BEdita API is up'

install:
  # Install Composer dependencies.
  - composer install --prefer-dist --no-interaction

script:
  # Run PHPUnit with coverage.
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  # Upload coverage report to CodeCov.io
  - bash <(curl -s https://codecov.io/bash)

jobs:
  fast_finish: true

  include:
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: "RUN=phpcs"
      script: |
        vendor/bin/phpcs -n -p --extensions=php \
          --standard=vendor/cakephp/cakephp-codesniffer/CakePHP \
          ./src ./tests
      after_success: skip
